apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: mateapp
  labels:
    app: todo-app
spec:
  replicas: 2 # 2 поди в стані спокою
  selector:
    matchLabels:
      app: todo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: leoleiden/todo-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi