apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-app-hpa
  namespace: mateapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-app-deployment
  minReplicas: 2 # Мінімум 2 поди
  maxReplicas: 5 # Максимум 5 подів
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Цільовий відсоток використання CPU
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70 # Цільовий відсоток використання Memory