apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: mateapp
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80 # Порт, який буде слухати LoadBalancer
      targetPort: 8080 # Порт контейнера, на якому слухає додаток
  type: LoadBalancer